- plugin/pom.xml
- plugin/src/main/java/com/spotify/plugin/dockerfile/AbstractDockerMojo.java
- plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java
- plugin/src/main/java/com/spotify/plugin/dockerfile/LoggingProgressHandler.java
- plugin/src/main/java/com/spotify/plugin/dockerfile/PushMojo.java
- plugin/src/main/java/com/spotify/plugin/dockerfile/TagMojo.java
This latest version of docker-client includes a change in the
`DefaultDockerClient.fromEnv()` so that on OS X it uses
`unix:///var/run/docker.sock` by default if DOCKER_HOST is not set (to
work with Docker for Mac out of the box).
In 4.x of the docker-client the package names of exception classes
changed as well.
> upgrade to docker-client:4.0.8

- plugin/src/it/advanced/frontend/src/test/java/com/spotify/it/frontend/MainIT.java
need to add a healthcheck to the TemporaryJob to avoid helios-testing
from thinking that the job is immediately available after the deploy
finishes.
see:
https://github.com/spotify/dockerfile-maven/pull/13#issuecomment-305355177
https://github.com/spotify/helios/issues/916#issuecomment-221090878
> fix MainIT to work on Docker for Mac

- README.md
- extension/pom.xml
- plugin/pom.xml
- plugin/src/main/java/com/spotify/plugin/dockerfile/AbstractDockerMojo.java
- pom.xml
Adds support for loading Google credentials from the environment variable DOCKER_GOOGLE_CREDENTIALS if it is set and points to a readable file.
If not set, then the Google Application Default Credentials are still used as before (if they can be loaded).
This PR also includes a change to use authentication info from the docker-cli config file, which in turn depends on some not-yet-released changes in docker-client (see https://github.com/spotify/docker-client/pull/775). This will resolve a number of open issues in this repository around a lack of authentication support.
The build will fail until https://github.com/spotify/docker-client/pull/775 is complete and released, but I wanted to create the PR now to start the review process.
In the cases where Google credentials are available, use …
> support for loading Google credentials from environment file

- pom.xml
The update to use com.spotify:foss-root in 55a04cc made a lot of this configuration in pom.xml redundant:
- configuration for the release plugin
- nexus-staging plugin
- the foss-root activates a release profile, which already has configuration for gpg/etc
- distributionManagement
> remove duplicated pom elements

- plugin/pom.xml
- plugin/src/it/basic-with-build-args/Dockerfile
- plugin/src/it/basic-with-build-args/pom.xml
- plugin/src/it/basic-with-build-args/verify.groovy
- plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java
This fixes issue #22. I took inspiration from the comments there and used the format below, let me know if you prefer another format.
```xml
<configuration>
<buildArgs>
<key>value</key>
</buildArgs>
</configuration>
```
> Add support for supplying build-args, fixes #22

- plugin/src/main/java/com/spotify/plugin/dockerfile/AbstractDockerMojo.java
This is a continuation of #35; I added a commit addressing my own feedback to be able to merge and release this quicker.
> allow disabling of Google Container Registry credential checks

- plugin/src/main/java/com/spotify/plugin/dockerfile/AbstractDockerMojo.java
- plugin/src/main/java/com/spotify/plugin/dockerfile/MavenRegistryAuthSupplier.java
A proposed fix for issue #64 .  Also adds the ability to configure the location of the docker configuration file if it's in a non-standard location.
> Fix for Issue 64

- .travis.yml
When the build was moved to use openjdk instead of oraclejdk, it broke snapshot deployment due to the `$TRAVIS_JDK_VERSION` clause.
> Fix snapshot deployment

- README.md
Please consider including documentation on the `buildArg` feature.
> Adding buildArg feature to example in README.md

- README.md
Provides documentation on skip options
Closes #103
Sometimes in a single project where we use this plugin we support two workflows:
+ Locally,  a developer will have `mvn package` driving the docker image building based on the `Dockerfile`
+ In continuous integration builds we use a multi-stage Dockerfile and have docker driving maven with `docker build -f Dockerfile.multistage .`
We found the undocumented skip properties very helpful for letting both workflows be supported in the same project, but they deserve documentation in the readme. This pull request provides that documentation. Thank you for your excellent work!
> Add skip option documentation

- plugin/pom.xml
- plugin/src/it/basic-with-build-args/Dockerfile
Incorporating recent security upgrades from docker-client:
* Bouncy Castle Cryptography APIs 1.52 (Mar 2015) -> 1.59 (Jan 2018)
* FasterXML Jackson 2.8.8 (Apr 2017) -> 2.9.4 (Jan 2018)
Upgrade of Guava is required by the Maven Enforcer (rule Require Upper Bound Dependencies).
> Security Upgrade: docker-client

- README.md
I was invited to suggest some language for the Readme to capture details I found useful in a [closed issue](https://github.com/spotify/dockerfile-maven/issues/69#issuecomment-365260709).
Two discrete sections, the first is about how Google Container Registry users can setup Application Default Credentials with links to additional documentation.
The second section is merely itemizing the plugin goals explicitly, like one would typically see in the standard Maven site for a plugin.
Purely suggestions, willing to cut or revise as you see fit.
> Add more GCR authentication CLI details

- .github/ISSUE_TEMPLATE.md
We get a lot of issues that are just questions on usage. Let's direct these
to StackOverflow and the docs so issues can be reserved for bugs and
feature requests.
> Update ISSUE_TEMPLATE.md to point questions to SO and docs

- README.md
- plugin/pom.xml
- plugin/src/it/maven-settings-auth/Dockerfile
- plugin/src/it/maven-settings-auth/auth.properties
- plugin/src/it/maven-settings-auth/invoker.properties
- plugin/src/it/maven-settings-auth/pom.xml
- plugin/src/it/maven-settings-auth/settings-security.xml
- plugin/src/it/maven-settings-auth/verify.groovy
- plugin/src/it/settings.xml
- plugin/src/main/java/com/spotify/plugin/dockerfile/MavenRegistryAuthSupplier.java
Thanks for this plugin!
We normally use encrypted passwords in `settings.xml` according to Maven's [password encryption instructions](https://maven.apache.org/guides/mini/guide-encryption.html).
This change allows Docker registry passwords to be stored in encrypted form in `settings.xml`, and accessed and decrypted via the usual `useMavenSettingsForAuth=true` property in the `dockerfile-maven` plugin.
Related issues:
https://github.com/spotify/dockerfile-maven/issues/78
https://github.com/spotify/dockerfile-maven/issues/84
https://github.com/spotify/dockerfile-maven/issues/122
> Support encrypted Maven server passwords in settings.xml

- plugin/pom.xml
Update docker-client version to updated client with fix for newer ecdsa key files.
The latest docker uses ecdsa instead of rsa keys.
> update docker-client version

- .travis.yml
- CHANGELOG.md
- plugin/pom.xml
update org.apache.maven:maven-archiver to resolve Java 11 issue
see https://github.com/spotify/dockerfile-maven/issues/77#issuecomment-331531574 - for some reason org.codehaus.plexus.archiver.zip.AbstractZipArchiver (which comes from a transitive dependency of maven-archiver) is throwing an exception on Java 11 when maven-archiver is at v3.0.0. Updated to latest (3.2.0) to pull in newer transitive dependencies.
Also upgraded a bunch of other dependencies that caused
requireUpperBoundsDep problems once maven-archiver was at 3.2.0
> update org.apache.maven:maven-archiver to resolve Java 11 issue 

- plugin/pom.xml
Java 8 is nearing EOL, so we can probably safely stop outputting 1.7
compatible classes
> update compiler source/target from 1.7 to 1.8

- README.md
See:
- spotify/dockerfile-maven#101
- spotify/dockerfile-maven#209
> Improve documentation on referencing build artifacts

- plugin/pom.xml
See CVE-2018-11771 https://nvd.nist.gov/vuln/detail/CVE-2018-11771.
> Upgrade org.apache.commons:comons-compress to fix vuln

- CHANGELOG.md
- docs/usage.md
- plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java
> Add support for --squash experimental build option

- plugin/src/main/java/com/spotify/plugin/dockerfile/AbstractDockerMojo.java
> Add parameter to skip docker-info jar creation.

- plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java
- plugin/src/test/java/com/spotify/plugin/dockerfile/TestRepoNameValidation.java
This change adds an early validation of repo names specified in the pom.  
An invalid name will now cause an early build failure with a clear message in the build log, rather than the incomprehensible “broken pipe” error at docker build time.
> Validation of docker repository names

- plugin/pom.xml
Fixes #278 
This update fixes issue described here https://github.com/spotify/docker-client/issues/875 about supporting Windows named pipes.
> Update docker-client version to 8.14.5

- plugin/src/main/java/com/spotify/plugin/dockerfile/BuildMojo.java
- plugin/src/test/java/com/spotify/plugin/dockerfile/TestRepoNameValidation.java
Adjusted regex validation to allow port number.
> #308 Extend repository validation by allowing port number.

- .grenrc.yml
- CHANGELOG.md
- README.md
[gren](https://github.com/github-tools/github-release-notes#installation)
can be used to automate creating Releases in Github and the changelog.
Since we already have a changelog file in the repo, I didn't replace it
(gren will sort the releases in the reverse order), but I did run `gren
release` for each past release to populate https://github.com/spotify/dockerfile-maven/releases
> update Changelog for 1.14.11 - 1.14.13, setup gren

- plugin/pom.xml
I noticed an automated Github security warning for
https://nvd.nist.gov/vuln/detail/CVE-2019-12402
> bump commons-compress to 1.19 for CVE-2019-12402
